name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Front End
        run: npm install && npm run build
        working-directory: ./mel-suggestion-front
      - name: Move files
        uses: canastro/copy-file-action@master
        with:
          source: "./mel-suggestion-front/dist/index.html"
          target: "./mel-suggestion-back/public/index.html"
        
