name: Release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build & test"
        run: npm install && npm run build
        working-directory: ./mel-suggestion-front
      - name: Move files
        uses: canastro/copy-file-action@master
        with:
          source: "./mel-suggestion-front/dist"
          target: "./mel-suggestion-back/public"

      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: "./mel-suggestion-back"
          dest: suggestion.zip
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Suggestion"
          files: suggestion.zip
